# version: '3' 

services:
    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres13:/var/lib/postgresql/data

    redis:
        image: redis:7.0.15-alpine
        ports:
            - "6379:6379"
        volumes:
            - redis:/data  

    web:
        container_name: rd.test.cart-ecommerce
        build: .
        image: rd-cart-ecommerce
        command: bash -c "bundle install && bin/rails s -b 0.0.0.0 -p 3000"
        volumes:
            - .:/rails
            - gems-data:/bundle
        ports:
           - "3000:3000"
        env_file: .env
        environment:
            RAILS_ENV: development
        depends_on:
            - db
            - redis

    sidekiq:
        container_name: rd.test.cart-ecommerce.sidekiq
        build: .
        image: rd-cart-ecommerce
        command: bundle exec sidekiq -c 4 -v
        volumes:
            - .:/rails
            - gems-data:/bundle
        env_file: .env
        environment:
            RAILS_ENV: development
        depends_on:
            - db
            - redis

    test:
        profiles: ["test"]
        build: .
        image: rd-cart-ecommerce
        command: bash -c "
            bundle install &&
            bin/rails db:create db:migrate &&
            bundle exec rspec
            "
        volumes:
            - .:/rails
            - gems-data:/bundle
        depends_on:
            - db
            - redis
        env_file: .env
        environment:
            RAILS_ENV: test
            DATABASE_URL: ${TEST_DATABASE_URL}

volumes:
    postgres13:
    redis:
    gems-data: